### ISSUE TITLE
pip install failed on missing CHANGES.rst

### ISSUE THREAD

**Issue by sheilatron** [zopefoundation/zope2.sessioncookie#1]
(etl)[sallen@localhost jivacore.utils]$ pip install zope2.sessioncookie
Collecting zope2.sessioncookie
  Downloading zope2.sessioncookie-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-RRfVp8/zope2.sessioncookie/setup.py", line 8, in <module>
        with open('CHANGES.rst') as f:
    IOError: [Errno 2] No such file or directory: 'CHANGES.rst'

**Comment by tseaver** [comment]
https://pypi.python.org/pypi/zope2.sessioncookie/0.6.1
